коды завершения, обработка ошибок (слегка)

diff --git a/send b/send
--- a/send
+++ b/send
@@ -1,6 +1,29 @@
 #! /bin/bash
+# send <номер телефона> <текст сообщения>
+
 dst=$1
 mess=$2
-#echo $2
-echo "  http://192.168.153.4/cgi/WebCGI?1500101=account=apiuser&password=utytpbc&port=1&destination=$dst&content=$mess" --quiet -O -
 
+#echo "  http://192.168.153.4/cgi/WebCGI?1500101=account=apiuser&password=utytpbc&port=1&destination=$dst&content=$mess" --quiet -O -
+#echo "http://192.168.153.4/cgi/WebCGI?1500101=account=apiuser&password=utytpbc&port=1&destination=$dst&content=$mess" --quiet -O -
+#wget "http://192.168.153.4/cgi/WebCGI?1500101=account=apiuser&password=utytpbc&port=1&destination=$dst&content=$mess" -T 5 -t 1 --quiet -O -
+
+echo "[$(date +%D\ \-\ %T)]----------------------------------------" | tee -a sms.log
+res=$(wget "http://192.168.1.33/send.html" -T 5 -t 1 --quiet -O -)
+
+	#   если пустая строка
+if  [[ -z $res ]]
+then
+	echo $dst | tee -a sms.log
+	echo "Error: can't send sms" | tee -a sms.log 
+	echo "---------------------------------------------------[$(date +%T)]" | tee -a sms.log
+
+	exit 1
+else
+	#
+	echo $dst | tee -a sms.log
+	echo "$res" | tee -a sms.log
+        echo "---------------------------------------------------[$(date +%T)]" | tee -a sms.log
+
+	exit 0
+fi
diff --git a/send_kartvit_sms b/send_kartvit_sms
--- a/send_kartvit_sms
+++ b/send_kartvit_sms
@@ -5,30 +5,50 @@
 #phones=$2
 kartvit=/home/andrew/work/sms/sms/kartvit.txt
 phones=/home/andrew/work/sms/phones.txt
+s=0
+e=0
+
 echo "start send..."
-echo "BEGIN-------------$(date +%D\ \-\ %T)" >> sms_kartvit.log
+echo "[$(date +%D\ \-\ %T)]----------------------------------" >> sms_kartvit.log
 	# если нужный файл существует
-if [ -f $kartvit ];
+if [ -e $kartvit ];
 then
 		# получаем список номеров и сумм (каждая строка вида 'номер-сумма' - отдельное сообщение)
 		# перебираем строки и отправляем СМС
+	tmp_file=$(./scan_kartvit $kartvit $phones)
 	while read line
 	do
+			# разбиваем строку по словам и выделяем номер и сумму
 		arr=($line)
 		dst=${arr[0]}
 		mess=${arr[1]}
-		#echo "http://192.168.153.4/cgi/WebCGI?1500101=account=apiuser&password=utytpbc&port=1&destination=$dst&content=$mess" --quiet -O -
-		#wget "http://192.168.153.4/cgi/WebCGI?1500101=account=apiuser&password=utytpbc&port=1&destination=$dst&content=$mess" -T 5 -t 1 --quiet -O -
-		#wget "http://192.168.1.33/send.html" -T 5 -t 1 --quiet -O - || echo "Error: can't send" | tee -a sms_kartvit.log 
-		echo "	$dst - OK" >> sms_kartvit.log
-        done < $(./scan_kartvit $kartvit $phones)
+			# отправляем СМС
+		./send $dst $mess
+			# проверяем результат отправки и выводим соответствующее сообщение
+		if [[ $? -eq 0 ]]
+		then
+			echo "	$dst - OK" | tee -a  sms_kartvit.log
+			s=$(($s + 1))
+		else
+			echo "	$dst - ERR"  | tee -a  sms_kartvit.log
+			e=$(($e + 1))
+		fi
+        done < $tmp_file
 
+	rm $tmp_file
+
+        echo "  Complete:  errors: $e; success: $s" | tee -a sms_kartvit.log
+	echo "---------------------------------------------[$(date +%T)]" >> sms_kartvit.log
+		# удаляем файл после обработки
+	rm $kartvit
+
+	exit 0
 else
-	echo "no file"
-	echo "	no file" >> sms_kartvit.log
+	echo "	Complete:  nothing to do" | tee -a  sms_kartvit.log
+	echo "---------------------------------------------[$(date +%T)]" >> sms_kartvit.log
+
+	exit 11
 fi
 
 
-echo "END---------------$(date +%D\ \-\ %T)" >> sms_kartvit.log
-rm $kartvit
-echo "Complete!"
+
